name: pysb-tutorial
channels:
  - alubbock
  - defaults
dependencies:
  - atomizer=1.0
  - bionetgen=2.5.1
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cython=0.29.23
  - decorator=5.0.9
  - gmp=6.2.1
  - gmpy2=2.0.8
  - intel-openmp=2021.2.0
  - matplotlib=3.3.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - ncurses=6.2
  - networkx=2.5
  - nfsim=1.12.1
  - numpy=1.20.2
  - numpy-base=1.20.2
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.1.1
  - pysb=1.12.0
  - python=3.8.10
  - python-dateutil=2.8.1
  - readline=8.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.4
  - sympy=1.8
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - simplepso==2.1.1
    - git+https://github.com/lolab-vu/earm.git
